(ns kotoba.lang.test
  "Property testing + assertion helpers for the kotoba foundational stdlib.
  Layer 4 (tooling).

  Provides a deterministic PRNG, an IGenerator protocol, primitive generators,
  and `quickcheck` / `for-all` that shrink failing cases. Pure functions, no
  host — runs on kotoba-WASM. Consumes kotoba-lang/spec (a spec can be a
  generator), making this lib a consumer of spec.

  Zero third-party runtime deps; .cljc (JVM / SCI / CLJS / GraalVM / kotoba-WASM)."
  (:refer-clojure :exclude [test rand-int])
  #?(:clj  (:require [kotoba.lang.spec :as spec])
     :cljs (:require [kotoba.lang.spec :as spec])))

;; ---------- deterministic PRNG (LCG, pure) ----------

(defrecord RNG [state])

(defn make-rng
  "Make a deterministic PRNG from a seed (long). LCG with 64-bit-ish constants,
  masked to 32 bits for JVM/CLJS parity."
  ([seed] (make-rng seed nil))
  ([seed _]
   (->RNG (bit-and (long seed) 0xFFFFFFFF))))

(defn- next-state [s]
  (bit-and (+ (* s 1103515245) 12345) 0x7FFFFFFF))

(defn next-long
  "Return `[n rng']` where n is a non-negative long in [0, 2^31)."
  [rng]
  (let [s (next-state (:state rng))]
    [s (->RNG s)]))

(defn next-int
  "Return `[n rng']` with n uniform in [`lo` `hi`] (inclusive)."
  ([rng hi] (next-int rng 0 hi))
  ([rng lo hi]
   (let [span (inc (long (- hi lo)))
         [n r] (next-long rng)]
     [(+ lo (mod n span)) r])))

;; ---------- IGenerator protocol ----------

(defprotocol IGenerator
  (gen [g rng] "Return [value rng'] generated by g from rng."))

;; ---------- primitive generators ----------

(defn gen-int
  "Generator of integers in [`lo` `hi`] (inclusive). Defaults to a small range
  biased toward finding edge cases quickly when used with shrink."
  ([rng] (gen-int rng -100 100))
  ([rng hi] (gen-int rng 0 hi))
  ([rng lo hi] (next-int rng lo hi)))

(defn gen-bool [rng]
  (let [[n r] (next-long rng)] [(zero? (mod n 2)) r]))

(defn gen-element
  "Generator that picks uniformly from `coll`."
  [rng coll]
  (let [v (vec coll)
        [i r] (next-int rng 0 (dec (count v)))]
    [(v i) r]))

(def ^:private alphabet
  "abcdefghijklmnopqrstuvwxyz0123456789")

(defn gen-string
  "Generator of strings of length up to `max-len` (default 10) from a small
  alphabet."
  ([rng] (gen-string rng 10))
  ([rng max-len]
   (let [[len r] (next-int rng 0 max-len)
         chars (vec alphabet)
         n (count chars)]
     (loop [i 0 r r out (transient [])]
       (if (>= i len)
         [(apply str (persistent! out)) r]
         (let [[k r2] (next-int r 0 (dec n))]
           (recur (inc i) r2 (conj! out (chars k)))))))))

;; ---------- shrinking ----------

(defn shrink-int
  "Shrink an integer toward zero, yielding a lazy seq of candidates (0 first,
  then halving toward the value)."
  [x]
  (if (zero? x)
    '()
    (let [x (long x)]
      (cons 0
            (->> (iterate #(quot % 2) x)
                 (take-while #(pos? (abs %)))
                 (distinct)
                 (remove #(= % x))
                 (map #(if (pos? x) (- x %) (+ x %))))))))

;; ---------- quickcheck ----------

(defn- try-shrink
  "Given a failing `value` and `prop`, walk shrink candidates to find the
  smallest one that still fails. Returns {:smallest :shrinks}."
  [value prop shrink-fn]
  (loop [smallest value shrinks 0]
    (let [candidates (shrink-fn smallest)
          failing (first (filter #(not (prop %)) candidates))]
      (if failing
        (recur failing (inc shrinks))
        {:smallest smallest :shrinks shrinks}))))

(defn quickcheck
  "Run `prop` (fn of one generated value -> truthy) `:runs` times (default 100)
  using `gen-fn` (fn of rng -> [value rng']) starting from `:seed` (default 0).
  On failure, shrinks via `:shrink` (default shrink-int, assumes integer values).

  Returns {:pass? bool :seed :runs} on pass, or
          {:pass? false :seed :runs :smallest :shrinks} on failure."
  [prop gen-fn & {:keys [seed runs shrink]
                  :or {seed 0 runs 100 shrink shrink-int}}]
  (loop [i 0 rng (make-rng seed)]
    (if (>= i runs)
      {:pass? true :seed seed :runs runs}
      (let [[v r] (gen-fn rng)]
        (if (prop v)
          (recur (inc i) r)
          (merge {:pass? false :seed seed :runs (inc i)}
                 (try-shrink v prop shrink)))))))

(defn for-all
  "Declarative property: `bindings` is [name gen-fn]*, `body` is the property
  expression (the last value is truthy on pass). Returns a fn of one generated
  tuple, suitable to pass to quickcheck with a tuple generator.

  NOTE: for the M1 surface this is a thin wrapper that builds a single-value
  property from the first binding; multi-var for-all lands with composite
  generators."
  [bindings body-fn]
  (let [[_name gen-fn] bindings]
    (fn [v] (body-fn v))))

;; ---------- assertion helpers ----------

(defn are-eq? [actual expected] (= actual expected))

(defn throws?
  "True iff `f` throws. Optionally matches `pred` against the ex-data/Message."
  ([f] (try (f) false (catch #?(:clj Throwable :cljs :default) _ true)))
  ([f pred] (try (f) false
                 (catch #?(:clj Throwable :cljs :default) e
                   (pred e)))))

;; ---------- spec bridge: a spec is a generator (value-shape only) ----------

(defn gen-from-spec
  "BEST-EFFORT generator from a kotoba.lang.spec spec. Only primitive types are
  generated (:int, :string, :boolean, :keyword, :any); composites return a
  placeholder. This is the seam that makes a spec a test generator (M5 consumer
  of spec)."
  [rng s]
  (case (:type s)
    :int     (gen-int rng -100 100)
    :boolean (gen-bool rng)
    :string  (gen-string rng 10)
    :keyword (let [[i r] (next-int rng 0 9)] [(keyword (str "k" i)) r])
    :any     (gen-int rng 0 99)
    :fn      (gen-int rng 0 9)        ; can't sample an arbitrary pred
    ;; composites: return a small scalar placeholder (M1 surface)
    (gen-int rng 0 9)))
